import { useSettings } from '../context/SettingsContext'

const LEVELS = [
  {
    value: 'A1',
    label: 'A1 — Beginner',
    description: 'Only the most basic 300 German words. Super simple sentences.',
  },
  {
    value: 'A2',
    label: 'A2 — Elementary',
    description: 'Common everyday vocabulary. Short, practical sentences.',
  },
  {
    value: 'B1',
    label: 'B1 — Intermediate',
    description: 'Wider vocabulary, moderate complexity. Some subordinate clauses.',
  },
  {
    value: 'B2',
    label: 'B2 — Upper-Intermediate',
    description: 'Rich vocabulary, varied grammar. Complex sentences allowed.',
  },
]

export default function Settings() {
  const { settings, updateSettings } = useSettings()

  return (
    <div className="flex flex-col min-h-screen pb-20">
      <div className="bg-slate-800 px-4 pt-12 pb-6">
        <h1 className="text-white text-2xl font-bold">Settings</h1>
        <p className="text-slate-400 text-sm mt-1">Customize your learning experience</p>
      </div>

      <div className="px-4 pt-6">
        <section>
          <h2 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
            Example Sentence Level
          </h2>
          <p className="text-slate-500 text-sm mb-4">
            Controls how complex the Claude-generated example sentences are.
          </p>
          <div className="space-y-2">
            {LEVELS.map(({ value, label, description }) => (
              <button
                key={value}
                onClick={() => updateSettings({ cefrLevel: value })}
                className={`w-full text-left p-4 rounded-xl border-2 transition-colors ${
                  settings.cefrLevel === value
                    ? 'border-blue-500 bg-blue-50'
                    : 'border-slate-200 bg-white hover:border-slate-300'
                }`}
              >
                <div className={`font-semibold text-sm ${
                  settings.cefrLevel === value ? 'text-blue-700' : 'text-slate-800'
                }`}>
                  {label}
                </div>
                <div className="text-slate-500 text-xs mt-0.5">{description}</div>
              </button>
            ))}
          </div>
        </section>

        <section className="mt-8">
          <h2 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
            About
          </h2>
          <div className="bg-white rounded-xl border border-slate-200 p-4 space-y-1.5 text-sm text-slate-600">
            <p>
              <strong>Dictionary data:</strong> English Wiktionary (CC BY-SA)
            </p>
            <p>
              <strong>Example sentences:</strong> Generated by Claude (Anthropic)
            </p>
            <p>
              <strong>Audio:</strong> Web Speech API (device TTS)
            </p>
            <p>
              <strong>Offline:</strong> IndexedDB via Dexie.js
            </p>
          </div>
        </section>
      </div>
    </div>
  )
}
